name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install pre-commit and tools
        run: |
          pip install pre-commit
          pre-commit --version

      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files

      - name: Lint (flake8)
        run: |
          pip install flake8
          flake8 --max-line-length=100 || true
